version: 0.0
os: linux
files:
  - source: /
    destination: /agsl
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 500
      runas: ec2-user
  AfterInstall:
    - location: scripts/docker_start.sh
      timeout: 300
      runas: ec2-user
