version: '3.9'

services:
 agsl-app-postgres:
   image: "postgres:15-alpine"
   command: postgres -c 'max_connections=1000'
   restart: always
   container_name: agsl-app-postgres-local
   environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres
   volumes:
     - ./db_data:/var/lib/postgresql/data
   ports:
     - "5666:5432"
