version: '3.9'

services:
 app:
   build:
     context: ./
     dockerfile: Dockerfile
   ports:
     - "3000:3002"
   environment:
     - NODE_ENV=production
 agsl-app-postgres:
   image: "postgres:15-alpine"
   command: postgres -c 'max_connections=1000'
   restart: always
   container_name: agsl-app-postgres-local
   environment:
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_USER=${DB_USERNAME}
     - POSTGRES_DB=${DB_NAME}
   volumes:
     - ./db_data:/var/lib/postgresql/data
   ports:
     - "${DB_PORT}:5432"

 agsl-app-pgAdmin:
   container_name: agsl-app-pgAdmin-local
   image: dpage/pgadmin4
   restart: always
   environment:
     - PGADMIN_DEFAULT_EMAIL=${DB_CLIENT_USERNAME}
     - PGADMIN_DEFAULT_PASSWORD=${DB_CLIENT_PASSWORD}
   ports:
     - "${DB_CLIENT_PORT}:80"

 nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  depends_on:
    - app
